// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "Suma.h"

std::string Suma::echo(const std::string& text)
{
    return "Hi, " + text;
}

int Suma::suma(int a, int b)
{
    return a + b;
}
